server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
gemini:
  api:
    key: AIzaSyDylAD3c3iCUaDH-l0k4NqLacGQ4Yg0ygg

spring:
  application:
    name: sentinel-api

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  mail:
    host: fake-smtp
    port: 1025
    properties:
      mail:
        smtp:
          auth: False

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm552535
    password: 030804
    driver-class-name: oracle.jdbc.OracleDriver

  messages:
    encoding: UTF-8
    basename: messages

  devtools:
    restart:
      enabled: true


logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE